
import { BibleBook, ReadingPhase } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // History (Jan-Feb)
  { name: '여호수아', chapters: 24, category: 'History' },
  { name: '사사기', chapters: 21, category: 'History' },
  { name: '룻기', chapters: 4, category: 'History' },
  { name: '사무엘상', chapters: 31, category: 'History' },
  { name: '사무엘하', chapters: 24, category: 'History' },
  { name: '열왕기상', chapters: 22, category: 'History' },
  { name: '열왕기하', chapters: 25, category: 'History' },
  { name: '역대상', chapters: 29, category: 'History' },
  { name: '역대하', chapters: 36, category: 'History' },
  { name: '에스라', chapters: 10, category: 'History' },
  { name: '느헤미야', chapters: 13, category: 'History' },
  { name: '에스더', chapters: 10, category: 'History' },
  
  // Law (Mar-Apr)
  { name: '창세기', chapters: 50, category: 'Law' },
  { name: '출애굽기', chapters: 40, category: 'Law' },
  { name: '레위기', chapters: 27, category: 'Law' },
  { name: '민수기', chapters: 36, category: 'Law' },
  { name: '신명기', chapters: 34, category: 'Law' },

  // Wisdom & Prophets (May-Sep)
  { name: '욥기', chapters: 42, category: 'WisdomProphets' },
  { name: '시편', chapters: 150, category: 'WisdomProphets' },
  { name: '잠언', chapters: 31, category: 'WisdomProphets' },
  { name: '전도서', chapters: 12, category: 'WisdomProphets' },
  { name: '아가', chapters: 8, category: 'WisdomProphets' },
  { name: '이사야', chapters: 66, category: 'WisdomProphets' },
  { name: '예레미야', chapters: 52, category: 'WisdomProphets' },
  { name: '예레미야 애가', chapters: 5, category: 'WisdomProphets' },
  { name: '에스겔', chapters: 48, category: 'WisdomProphets' },
  { name: '다니엘', chapters: 12, category: 'WisdomProphets' },
  { name: '호세아', chapters: 14, category: 'WisdomProphets' },
  { name: '요엘', chapters: 3, category: 'WisdomProphets' },
  { name: '아모스', chapters: 9, category: 'WisdomProphets' },
  { name: '오바댜', chapters: 1, category: 'WisdomProphets' },
  { name: '요나', chapters: 4, category: 'WisdomProphets' },
  { name: '미가', chapters: 7, category: 'WisdomProphets' },
  { name: '나훔', chapters: 3, category: 'WisdomProphets' },
  { name: '하박국', chapters: 3, category: 'WisdomProphets' },
  { name: '스바냐', chapters: 3, category: 'WisdomProphets' },
  { name: '학개', chapters: 2, category: 'WisdomProphets' },
  { name: '스가랴', chapters: 14, category: 'WisdomProphets' },
  { name: '말라기', chapters: 4, category: 'WisdomProphets' },

  // New Testament (Oct-Dec)
  { name: '마태복음', chapters: 28, category: 'NewTestament' },
  { name: '마가복음', chapters: 16, category: 'NewTestament' },
  { name: '누가복음', chapters: 24, category: 'NewTestament' },
  { name: '요한복음', chapters: 21, category: 'NewTestament' },
  { name: '사도행전', chapters: 28, category: 'NewTestament' },
  { name: '로마서', chapters: 16, category: 'NewTestament' },
  { name: '고린도전서', chapters: 16, category: 'NewTestament' },
  { name: '고린도후서', chapters: 13, category: 'NewTestament' },
  { name: '갈라디아서', chapters: 6, category: 'NewTestament' },
  { name: '에베소서', chapters: 6, category: 'NewTestament' },
  { name: '빌립보서', chapters: 4, category: 'NewTestament' },
  { name: '골로새서', chapters: 4, category: 'NewTestament' },
  { name: '데살로니가전서', chapters: 5, category: 'NewTestament' },
  { name: '데살로니가후서', chapters: 3, category: 'NewTestament' },
  { name: '디모데전서', chapters: 6, category: 'NewTestament' },
  { name: '디모데후서', chapters: 4, category: 'NewTestament' },
  { name: '디도서', chapters: 3, category: 'NewTestament' },
  { name: '빌레몬서', chapters: 1, category: 'NewTestament' },
  { name: '히브리서', chapters: 13, category: 'NewTestament' },
  { name: '야고보서', chapters: 5, category: 'NewTestament' },
  { name: '베드로전서', chapters: 5, category: 'NewTestament' },
  { name: '베드로후서', chapters: 3, category: 'NewTestament' },
  { name: '요한일서', chapters: 5, category: 'NewTestament' },
  { name: '요한이서', chapters: 1, category: 'NewTestament' },
  { name: '요한삼서', chapters: 1, category: 'NewTestament' },
  { name: '유다서', chapters: 1, category: 'NewTestament' },
  { name: '요한계시록', chapters: 22, category: 'NewTestament' },
];

export const PHASE_CONFIG = [
  { name: ReadingPhase.HISTORY, months: [0, 1], category: 'History' },
  { name: ReadingPhase.LAW, months: [2, 3], category: 'Law' },
  { name: ReadingPhase.WISDOM, months: [4, 5, 6, 7, 8], category: 'WisdomProphets' },
  { name: ReadingPhase.NEW_TESTAMENT, months: [9, 10, 11], category: 'NewTestament' },
];
